name: driver_neighbours
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy=2.3.0
  - pandas=2.3.1
  - scipy=1.16.0
  - graph-tool=2.97
  - ipywidgets=8.1.7
  - joblib=1.5.1
  - jupyterlab=4.4.5
  - pyspark=4.0.0
  - pip
  - pip:
      - omnipath
